[package]
name = "qp-postgres-v0_1-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
qp-postgres = "0.1.0"
tokio = { version = "1.15.0", features = ["full"] }

[[bench]]
name = "bench_main"
harness = false
