[package]
name = "bb8-v0_7-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
bb8 = "0.7.1"
tokio = { version = "1.15.0", features = ["full"] }

[[bench]]
name = "bench_main"
harness = false
