[package]
name = "bb8-postgres-v0_7-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
bb8 = "0.7.1"
bb8-postgres = "0.7.0"
tokio = { version = "1.15.0", features = ["full"] }

[[bench]]
name = "bench_main"
harness = false
