[package]
name = "deadpool-v0_9-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
deadpool = "0.9.2"
tokio = { version = "1.15.0", features = ["full"] }

[[bench]]
name = "bench_main"
harness = false
